version : '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - farline_static_volume:/Toss-master/static
      - farline_files_volume:/Toos-master/files
    networks:
      - nginx_network

volumes:
  farline_static_volume:
    external: true
  farline_files_volume:
    external: true
networks:
  nginx_network:
    external: true
